.TH POPULARITY_IMPORT 1
.SH NAME
popularity_import \- Import utility for Popularity adaptive entertainment shuffler
.SH SYNOPSIS
popularity_import libpq_connect_string < null_delimited_list_of_files
.SH EXAMPLE
popularity_find_music ~/my-music-library | popularity_import 'host=yourbusiness.popularity.life dbname=yourbusiness user=you'
.SH DESCRIPTION
popularity_import reads the files whose names you feed it on stdin (delimited by nulls), calculates hashes of thsoe files, and imports the hashes and file paths into your database so Popularity will include the files in your shuffle.
.PP
popularity_import will not update hashes of files that have changed. They get imported as new records. Updating hashes is not yet implemented but can be done by manually updating the databases. The hashes are SHA1 like the standard command line utilities would calculate.
.SH "SEE ALSO"
popularity-player(7), popularity_rebalance(1), popularity_clear_dead_paths(1), popularity_print_new_paths(1)
.SH COPYRIGHT
Copyright 2017 Michael Redman <michael.redman.4@gmail.com>
.br
GPL License
.SH IN GOD WE TRVST.
