.TH POPULARITY 7
.SH NAME
Popularity \- Adaptive entertainment shuffler
.SH DESCRIPTION
.B Popularity
is an adaptive entertainment shuffler that can process audience feedback collected over the Internet.
.SH MODULES
Popularity consists of the repositories \fBpopularity-common\fR, of which this page is a part, and also \fBpopularity-player\fR for audio and video, and \fBpopularity-slideshow\fR for still images.
So, you will need to install both \fBpopularity-common\fR, and at least one of \fBpopularity-player\fR and \fBpopularity-slideshow\fR, to use Popularity.
.PP
popularity-common, popularity-player, and popularity-slideshow are all hosted at https://github.com/michael-redman
.SH DATABASE CONFIGURATION
Popularity stores its data in a Postgresql database. If you are a Popularity commercial customer, you do not need to set up a database, instead credentials will be provided to you. If you are a "free" user you will need to set up a database yourself, see the popularity-player or popularity-slideshow documentation for further information.
.SH IMPORTING FILES
To use Popularity with your media collection, you first scan it with \fBpopularity_import\fR, and then build an initial probability distribution with \fBpopularity_rebalance\fR. See the manual pages for those commands for further information.
.SH MAINTENANCE
You will want to run \fBpopularity_rebalance\fR from time to time to rebuild the probablity distribution cache file with current information from the database, which will take into account votes or new files since the last rebuild. You can set up a cron job to do this. See the \fBpopularity_rebalance\fR(1) manual page for further information.
.SH "SEE ALSO"
popularity-player(7), popularity_import(1), popularity_rebalance(1), popularity_clear_dead_paths(1), popularity_print_new_paths(1)

.SH COPYRIGHT

Copyright 2017 Michael Redman <michael.redman.4@gmail.com>
.PP
GPL License

.SH IN GOD WE TRVST.
