#!/bin/sh

USE="libpq_connect_string [-h host] [-U username] dbname"

while	getopts "h:U:" opt; do
	case	"$opt" in
		h)	libpq_host_arg=" host=$OPTARG" ;;
		U)	libpq_user_arg=" user=$OPTARG" ;;
		\?)	echo "$USE" >&2; exit 1;t; esac; done
if [ $(($#-$OPTIND)) -ne 0 ]; then echo "$USE"; exit 1; fi
shift $(expr $OPTIND - 1)
db_name="$1"
libpq_connect_string="$libpq_host_arg$libpq_user_arg dbname=$db_name"
libpq_connect_string="`echo -n "$libpq_connect_string" | sed 's/^ *//g'`"
echo -n "$libpq_connect_string"

#IN GOD WE TRVST.
