#!/bin/sh

USE="popularity_rebalance [-h host] [-U username] dbname"

while	getopts "h:U:" opt; do
	case	"$opt" in
		h)	psql_host_arg="-h $OPTARG" ;;
		U)	psql_user_arg="-U $OPTARG" ;;
		\?)	echo "$USE" >&2; exit 1;t; esac; done
if [ $(($#-$OPTIND)) -ne 0 ]; then echo "$USE"; exit 1; fi
shift $(expr $OPTIND - 1)
db_name=$1
libpq_connect_string="`popularity_libpq_connect_string $psql_host_arg $psql_user_arg $db_name`"
target_dir="$HOME/.popularity/$libpq_connect_string"
mkdir -p "$target_dir"
target_nstates="`psql $psql_host_arg $psql_user_arg -Atc "select max_sn1()" $db_name`"
if	[ "$target_nstates" -eq 0 ]
	then	popularity_mkdist /tmp/$$ "$libpq_connect_string" 0
		mv /tmp/$$ "$target_dir"/max_sn1.dist
	else	popularity_focuser_bstep $psql_host_arg $psql_user_arg $db_name max_sn1 "$target_nstates"; fi
psql $psql_host_arg $psql_user_arg -c "delete from cache" $db_name

#IN GOD WE TRVST.
