.TH POPULARITY_REBALANCE 1
.SH NAME
popularity_rebalance \- Rebuilds Popularity probability distribution cache
.SH SYNOPSIS
popularity_rebalance [ -h db_host ] [ -U db_user_name ] db_name 
.SH EXAMPLE
popularity_rebalance -h yourbusiness.popularity.life -U you yourbusiness
.SH DESCRIPTION
popularity_rebalance rebuilds the probability distribution cache file that the Popularity player uses. It is important to rebuild this file periodically to take new votes into account.
.SH OPTIONS
.TP
-h Specify a database server hostname
.TP
-U Specify a database user name
.SH NOTES
\fBpopularity_rebalance\fR could take several minutes or longer to run, depending on the number of items in your collection and the speed of your network connection to the database.
.PP
When there are few votes in the system, popularity_rebalance builds a uniform probability distribution (all songs get equal probability). When sufficient votes accumulate, popularity_rebalance begins skewing the distribution towards more popular songs.
.PP
Consider setting up a daily cron job to run popularity_rebalance. You can do this by running the command "crontab -e", which will open your crontab file in an editor. Add a line with the rebalance command with your database host and username to the bottom of the file according to the following example, save the file, and exit the editor
.PP
@daily	/usr/local/bin/popularity_rebalance -h yourbusiness.popularity.life -U you yourbusiness
.SH "SEE ALSO"
popularity-player(7), popularity_import(1), popularity_clear_dead_paths(1), popularity_print_new_paths(1)
.SH COPYRIGHT
Copyright 2017 Michael Redman <michael.redman.4@gmail.com>
.PP
GPL License
.SH IN GOD WE TRVST.
