.TH POPULARITY_PLAYER_INIT_DB 1
.SH NAME
popularity_player_init_db \- Install schema and stored procedures for Popularity Shuffler
.SH SYNOPSIS
popularity_player_init_db [ -h db_host ] [ -U db_user_name ] db_name 
.SH EXAMPLE
popularity_player_init_db -h yourbusiness.popularity.life -U you yourbusinessdb
.SH DESCRIPTION
popularity_player_init_db initializes a Postgres database for use with Popularity Shuffler by installing the database schema and stored procedures.
.SH OPTIONS
.TP
-h Specify a database server hostname
.TP
-U Specify a database user name
.SH "SEE ALSO"
popularity-player(7), popularity_import(1)
.SH COPYRIGHT
Copyright 2017 Michael Redman <michael.redman.4@gmail.com>
.PP
GPL License
.SH IN GOD WE TRVST.
