#!/bin/sh

USE="popularity_player_init_db [-h host] [-U username] dbname"

while	getopts "h:U:" opt; do
	case	"$opt" in
		h)	psql_host_arg="-h $OPTARG" ;;
		U)	psql_user_arg="-U $OPTARG" ;;
		\?)	echo "$USE" >&2; exit 1;t; esac; done
if [ $(($#-$OPTIND)) -ne 0 ]; then echo "$USE"; exit 1; fi
shift $(expr $OPTIND - 1)
db_name=$1
cat /usr/local/share/popularity/common/sql/* | psql $psql_host_arg $psql_user_arg "$db_name"
cat /usr/local/share/popularity/player/sql/* | psql $psql_host_arg $psql_user_arg "$db_name"

#IN GOD WE TRVST.
