#!/bin/sh

USE="popularity_shuffler [-h host] [-U username] dbname"

while	getopts "h:U:" opt; do
	case	"$opt" in
		h)	psql_host_arg="-h $OPTARG" ;;
		U)	psql_user_arg="-U $OPTARG" ;;
		\?)	echo "$USE" >&2; exit 1;t; esac; done
if [ $(($#-$OPTIND)) -ne 0 ]; then echo "$USE"; exit 1; fi
shift $(expr $OPTIND - 1)
db_name=$1
libpq_connect_string="`popularity_libpq_connect_string $psql_host_arg $psql_user_arg $db_name`"
target_dir="$HOME/.popularity/$libpq_connect_string"
while true; do popularity_player "$libpq_connect_string" "$target_dir"/max_sn1.dist; done

#IN GOD WE TRVST.
