#!/bin/sh -e
IFS='
'
find $@ -type f \( -iname '*.jpg' -or -iname '*.jpeg' -or -iname '*.gif' -or -iname '*.bmp' -or -iname '*.tif' -or -iname '*.tiff' -or -iname '*.pcx' -or -iname '*.png' \) -print0
